<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF5MKO2e\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF5MKO2e/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF5MKO2e.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF5MKO2e\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerF5MKO2e\App_KernelDevDebugContainer([
    'container.build_hash' => 'F5MKO2e',
    'container.build_id' => '317ad4b9',
    'container.build_time' => 1649681018,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF5MKO2e');
